/**
 * Entity Test Runner
 *
 * SRP: Run all applicable scenarios for an entity based on its metadata.
 *
 * PRINCIPLE: No if/else per entity. Scenarios self-select based on metadata.
 *
 * Usage in test file:
 *
 *   const { runEntityTests } = require('../../factory/runner');
 *   runEntityTests('customer');
 *
 * Or with specific scenario categories:
 *
 *   runEntityTests('customer', { categories: ['crud', 'validation'] });
 */

const allMetadata = require('../../config/models');
const scenarios = require('./scenarios');
const { buildTestContext } = require('./data/test-context');
const entityFactory = require('./data/entity-factory');

/**
 * Run all test scenarios for an entity
 *
 * @param {string} entityName - Entity to test (e.g., 'customer', 'user')
 * @param {Object} options - Configuration options
 * @param {string[]} options.categories - Which scenario categories to run (default: all)
 * @param {Object} options.app - Express app instance (required)
 * @param {Object} options.db - Database pool (required)
 */
function runEntityTests(entityName, options = {}) {
  const meta = { ...allMetadata[entityName], entityName };

  if (!meta.tableName) {
    throw new Error(`Unknown entity: ${entityName}`);
  }

  const categoriesToRun = options.categories || Object.keys(scenarios);

  describe(`${entityName} Integration Tests`, () => {
    let ctx;

    beforeAll(async () => {
      if (!options.app || !options.db) {
        throw new Error('runEntityTests requires options.app and options.db');
      }
      ctx = buildTestContext(options.app, options.db);
    });

    // Note: We intentionally do NOT reset the counter between tests.
    // The counter + runId provides guaranteed uniqueness across all tests.

    afterEach(async () => {
      if (ctx) await ctx.cleanup();
    });

    // Run each scenario category
    for (const category of categoriesToRun) {
      const categoryScenarios = scenarios[category];
      if (!categoryScenarios) {
        console.warn(`Unknown scenario category: ${category}`);
        continue;
      }

      describe(`${category}`, () => {
        // Run each scenario in the category
        for (const [scenarioName, scenarioFn] of Object.entries(categoryScenarios)) {
          // Create a lazy context that accesses ctx at runtime
          const lazyCtx = {
            get request() { return ctx.request; },
            get db() { return ctx.db; },
            get factory() { return ctx.factory; },
            get authHeader() { return ctx.authHeader; },
            get authHeaderForUser() { return ctx.authHeaderForUser; },
            get getTestUser() { return ctx.getTestUser; },
            get entityNameFromTable() { return ctx.entityNameFromTable; },
            it: (name, fn) => it(name, fn),
            expect: expect,
          };
          
          // Scenarios self-select: if preconditions not met, they return early
          scenarioFn(meta, lazyCtx);
        }
      });
    }
  });
}

/**
 * Run tests for all entities
 * Useful for cross-cutting validation
 *
 * @param {Object} options - Same as runEntityTests
 */
function runAllEntityTests(options = {}) {
  const entityNames = Object.keys(allMetadata);

  for (const entityName of entityNames) {
    runEntityTests(entityName, options);
  }
}

/**
 * Create a minimal test file for an entity
 * Returns the test file content as a string
 *
 * @param {string} entityName
 * @returns {string} Test file content
 */
function generateTestFile(entityName) {
  return `/**
 * ${entityName} Integration Tests
 *
 * Auto-generated by test factory. Edit only if entity-specific overrides needed.
 */

const { runEntityTests } = require('../../factory/runner');
const { setupTestDatabase, cleanupTestDatabase } = require('../../helpers/test-db');
const app = require('../../../server');
const db = require('../../../db/connection');

describe('${entityName}', () => {
  beforeAll(async () => {
    await setupTestDatabase();
  });

  afterAll(async () => {
    await cleanupTestDatabase();
  });

  runEntityTests('${entityName}', {
    app,
    db: db.pool,
    // Uncomment to run only specific categories:
    // categories: ['crud', 'validation'],
  });
});
`;
}

module.exports = {
  runEntityTests,
  runAllEntityTests,
  generateTestFile,
};
